# AUTOGENERATED! DO NOT EDIT! File to edit: ../titanic.ipynb.

# %% auto 0
__all__ = ['iskaggle', 'creds', 'cred_path', 'path', 'df']

# %% ../titanic.ipynb 1
import os
from dotenv import load_dotenv
from pathlib import Path
from fastai.tabular.all import *


# %% ../titanic.ipynb 2
iskaggle = os.environ.get('KAGGLE_KERNEL_RUN_TYPE', '')
creds = ''

# %% ../titanic.ipynb 3
cred_path = Path('~/.kaggle/kaggle.json').expanduser()
if not cred_path.exists():
    cred_path.parent.mkdir(exist_ok=True)
    cred_path.write_text(creds)
    cred_path.chmod(0o600)

# %% ../titanic.ipynb 4
path = Path('titanic')

# %% ../titanic.ipynb 5
if not iskaggle and not path.exists():
    import zipfile, kaggle
    kaggle.api.competition_download_cli(str(path))
    zipfile.ZipFile(f'{path}.zip').extractall(path)

# %% ../titanic.ipynb 6
if iskaggle:
    path = Path('../input/titanic')
    ! pip install -q datasets

# %% ../titanic.ipynb 8
import pandas as pd

# %% ../titanic.ipynb 9
df = pd.read_csv(path/'train.csv')
